### ISSUE TITLE
Does not work on Zabbix 4.4

### ISSUE THREAD

**Issue by slawomirs** [asand3r/zbx-beserver#1]
Item is not supppoted . Error: `Cannot connect to ODBC DSN: [SQL_ERROR]:[HY090][0][[unixODBC][Driver Manager]Invalid string or buffer length]`

**Comment by asand3r** [comment]
Ok, so configure your DSN/FreeTDS/unixODBC. It's not the template issue.

**Comment by slawomirs** [comment]
Yeah, I agree this is not the template. But I found also some typo's, like in the key: db.odbc.get[all.jobs.satus,FAGBOK-BACKUP]. Should not be there 'status' instead? Does it matter? Also in the template file there is db.odbc.get[all.josb.satus. SHould not be jobs?
Slawomir
